import {
  Bot,
  Code,
  Image as ImageIcon,
  FileText,
  Zap,
  FileJson,
  TestTube,
  Hash,
  Key,
  Package,
  Scissors,
  FileCode,
  Database,
  Braces,
  LayoutGrid,
  GitCompare,
  Type,
  CaseSensitive,
  ArrowLeftRight,
  FileSearch,
  MessageSquare,
  Volume2,
  QrCode,
  Shield,
  Link2,
  FileImage,
  Calculator,
  Palette,
  Clock,
  Calendar,
  Sparkles,
  CheckCircle,
  Pencil,
  Eraser,
  Wand2,
  Image,
  Crop,
  Droplets,
  Settings,
  PenTool,
  AlignLeft,
  Lock,
  BookOpen,
  ClipboardCheck,
  Search,
  GitBranch,
  Workflow,
  DollarSign,
  Paintbrush,
  ArrowDown,
  List,
  RotateCcw,
  Space,
  ArrowUpDown,
  Film,
  Layers,
  ScanText,
  Play,
  Sparkle,
  ImagePlus,
} from "lucide-react"

export type ToolCategory = "AI Tools" | "Developer Tools" | "Image Tools" | "Text Tools" | "Productivity"

export interface Tool {
  id: string
  name: string
  description: string
  category: ToolCategory
  icon: any
  href: string
  features: string[]
  popular: boolean
  usageCount?: number
  new?: boolean
}

export const tools: Tool[] = [
  {
    id: "ai-text-humanizer",
    name: "AI Text Humanizer",
    description: "Convert AI-generated text to sound more natural and human-like",
    category: "AI Tools",
    icon: Bot,
    href: "/tools/ai-tools/ai-humanizer",
    features: ["Natural language", "Multiple tones", "Instant results"],
    popular: true,
    usageCount: 15420,
  },
  {
    id: "ai-content-detector",
    name: "AI Content Detector",
    description: "Detect whether text was generated by AI or written by humans",
    category: "AI Tools",
    icon: CheckCircle,
    href: "/tools/ai-tools/ai-detector",
    features: ["High accuracy", "Detailed report", "Fast scanning"],
    popular: true,
    usageCount: 12350,
  },
  {
    id: "smart-paraphraser",
    name: "Smart Paraphraser",
    description: "Rewrite text while maintaining original meaning and context",
    category: "AI Tools",
    icon: Pencil,
    href: "/tools/ai-tools/paraphraser",
    features: ["Context-aware", "Multiple styles", "Plagiarism-free"],
    popular: true,
    usageCount: 8900,
  },
  {
    id: "grammar-checker",
    name: "Grammar Checker",
    description: "Check and correct grammar, spelling, and punctuation errors",
    category: "AI Tools",
    icon: CheckCircle,
    href: "/tools/ai-tools/grammar-checker",
    features: ["Real-time check", "Suggestions", "Explanation"],
    popular: true,
    usageCount: 18750,
  },
  {
    id: "ai-resume-builder",
    name: "AI Resume Builder",
    description: "Create professional resumes with AI-powered suggestions",
    category: "AI Tools",
    icon: FileText,
    href: "/tools/ai-tools/resume-builder",
    features: ["ATS-friendly", "Multiple templates", "AI optimization"],
    popular: true,
    usageCount: 6540,
    new: true,
  },
  {
    id: "ocr-image-to-text",
    name: "OCR Image to Text",
    description: "Extract text from images using free offline OCR powered by Tesseract.js",
    category: "AI Tools",
    icon: ScanText,
    href: "/tools/ai-tools/ocr-image-to-text",
    features: ["Offline OCR", "Browser AI", "100% Private"],
    popular: true,
    usageCount: 14800,
    new: true,
  },
  {
    id: "image-super-compressor",
    name: "Image Super Compressor",
    description: "Shrink image files by 90% without quality loss using browser AI",
    category: "AI Tools",
    icon: Zap,
    href: "/tools/ai-tools/image-super-compressor",
    features: ["90% smaller", "Browser AI", "Quality control"],
    popular: true,
    usageCount: 12400,
    new: true,
  },
  {
    id: "code-to-image",
    name: "Code to Image",
    description: "Create beautiful syntax snapshots for social media and docs",
    category: "AI Tools",
    icon: Code,
    href: "/tools/ai-tools/code-to-image",
    features: ["Multiple themes", "No watermark", "High quality"],
    popular: false,
    usageCount: 9200,
    new: true,
  },
  {
    id: "voice-to-text",
    name: "Voice to Text",
    description: "Free voice typing with instant browser transcription using Web Speech API",
    category: "AI Tools",
    icon: Volume2,
    href: "/tools/ai-tools/voice-to-text",
    features: ["Real-time", "Browser AI", "100% Private"],
    popular: false,
    usageCount: 8600,
    new: true,
  },
  {
    id: "pdf-sanitizer",
    name: "PDF Metadata Remover",
    description: "Remove all metadata from PDFs to protect your privacy",
    category: "AI Tools",
    icon: Shield,
    href: "/tools/ai-tools/pdf-sanitizer",
    features: ["Privacy first", "Browser-based", "Clean PDFs"],
    popular: false,
    usageCount: 7100,
    new: true,
  },
  {
    id: "ai-background-remover-pro",
    name: "AI Background Remover Pro",
    description: "Advanced AI background removal using WebAssembly in your browser",
    category: "AI Tools",
    icon: Scissors,
    href: "/tools/ai-tools/ai-background-remover-pro",
    features: ["WASM powered", "Private", "HD quality"],
    popular: false,
    usageCount: 6800,
    new: true,
  },
  {
    id: "video-to-gif",
    name: "Video to GIF Converter",
    description: "Convert videos to GIFs using browser-based FFmpeg",
    category: "AI Tools",
    icon: Film,
    href: "/tools/ai-tools/video-to-gif",
    features: ["FFmpeg WASM", "No uploads", "Free forever"],
    popular: false,
    usageCount: 5900,
    new: true,
  },
  {
    id: "sentiment-analyzer",
    name: "Sentiment Analyzer",
    description: "Analyze text sentiment and emotions using local AI models",
    category: "AI Tools",
    icon: MessageSquare,
    href: "/tools/ai-tools/sentiment-analyzer",
    features: ["Emotion detect", "Browser AI", "Private"],
    popular: false,
    usageCount: 5200,
    new: true,
  },
  {
    id: "password-vault",
    name: "Password Vault",
    description: "Generate secure passwords and encrypt notes with Web Crypto API",
    category: "AI Tools",
    icon: Lock,
    href: "/tools/ai-tools/password-vault",
    features: ["Web Crypto", "Secure", "Browser-only"],
    popular: false,
    usageCount: 4700,
    new: true,
  },
  {
    id: "face-blur",
    name: "Face Blur Tool",
    description: "Automatically detect and blur faces in photos for privacy protection",
    category: "AI Tools",
    icon: Shield,
    href: "/tools/ai-tools/face-blur",
    features: ["Auto detect", "Privacy first", "Browser AI"],
    popular: false,
    usageCount: 4300,
    new: true,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON data with syntax highlighting",
    category: "Developer Tools",
    icon: FileJson,
    href: "/tools/developer-tools/json-formatter",
    features: ["Syntax highlighting", "Error detection", "Minify/Beautify"],
    popular: true,
    usageCount: 25680,
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings and files instantly",
    category: "Developer Tools",
    icon: Hash,
    href: "/tools/developer-tools/base64-encoder-decoder",
    features: ["Text & files", "Copy to clipboard", "Bidirectional"],
    popular: true,
    usageCount: 19450,
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress images without losing quality - reduce file size up to 80%",
    category: "Image Tools",
    icon: ImageIcon,
    href: "/tools/image-tools/image-compressor",
    features: ["Lossless/Lossy", "Batch processing", "Preview results"],
    popular: true,
    usageCount: 22180,
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove background in 1-click. HD quality for product photos and portraits",
    category: "Image Tools",
    icon: Scissors,
    href: "/tools/image-tools/background-remover",
    features: ["1-click remove", "HD quality", "No signup"],
    popular: true,
    usageCount: 18900,
    new: true,
  },
  {
    id: "social-media-resizer",
    name: "Social Media Resizer",
    description: "One image, every social size instantly. 8 platforms covered",
    category: "Image Tools",
    icon: Crop,
    href: "/tools/image-tools/social-media-resizer",
    features: ["8 platforms", "Batch resize", "Instant download"],
    popular: true,
    usageCount: 15600,
    new: true,
  },
  {
    id: "webp-converter",
    name: "WebP Converter",
    description: "Reduce image size by 90% without losing quality",
    category: "Image Tools",
    icon: Zap,
    href: "/tools/image-tools/webp-converter",
    features: ["90% smaller", "Quality control", "WebP format"],
    popular: true,
    usageCount: 14200,
    new: true,
  },
  {
    id: "image-watermarker",
    name: "Image Watermarker",
    description: "Watermark 100 photos in 5 seconds. Protect your work",
    category: "Image Tools",
    icon: Droplets,
    href: "/tools/image-tools/image-watermarker",
    features: ["Bulk watermark", "Text & logo", "Fast processing"],
    popular: false,
    usageCount: 8400,
    new: true,
  },
  {
    id: "mockup-generator",
    name: "Mockup Generator",
    description: "Turn screenshots into professional marketing assets",
    category: "Image Tools",
    icon: Layers,
    href: "/tools/image-tools/mockup-generator",
    features: ["Browser frames", "MacBook mockup", "Gradients"],
    popular: false,
    usageCount: 7200,
    new: true,
  },
  {
    id: "image-to-text",
    name: "Image to Text OCR",
    description: "Extract text from images instantly with free OCR",
    category: "Image Tools",
    icon: ScanText,
    href: "/tools/image-tools/image-to-text",
    features: ["Free OCR", "Instant extract", "Copy text"],
    popular: false,
    usageCount: 12800,
    new: true,
  },
  {
    id: "thumbnail-previewer",
    name: "Thumbnail Previewer",
    description: "Predict which thumbnail gets more views with A/B test",
    category: "Image Tools",
    icon: Play,
    href: "/tools/image-tools/thumbnail-previewer",
    features: ["A/B testing", "YouTube UI", "Preview mode"],
    popular: false,
    usageCount: 5900,
    new: true,
  },
  {
    id: "svg-colorizer",
    name: "SVG Colorizer",
    description: "Instantly change any icon color without Illustrator",
    category: "Image Tools",
    icon: Paintbrush,
    href: "/tools/image-tools/svg-colorizer",
    features: ["Color picker", "Live preview", "SVG export"],
    popular: false,
    usageCount: 6300,
    new: true,
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate all website icons in 1-click from one image",
    category: "Image Tools",
    icon: ImagePlus,
    href: "/tools/image-tools/favicon-generator",
    features: ["All sizes", "1-click gen", "Download zip"],
    popular: false,
    usageCount: 9100,
    new: true,
  },
  {
    id: "photo-filter",
    name: "Photo Filter",
    description: "Give your photos the viral cyberpunk look with glitch effects",
    category: "Image Tools",
    icon: Sparkle,
    href: "/tools/image-tools/photo-filter",
    features: ["Glitch effect", "Retrowave", "VHS style"],
    popular: false,
    usageCount: 7800,
    new: true,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences, and estimate reading time",
    category: "Text Tools",
    icon: Type,
    href: "/tools/text-tools/word-counter",
    features: ["Real-time count", "Reading time", "Character stats"],
    popular: true,
    usageCount: 31240,
  },
  {
    id: "case-converter",
    name: "Text Case Converter",
    description: "Convert text to uppercase, lowercase, title case, and sentence case",
    category: "Text Tools",
    icon: CaseSensitive,
    href: "/tools/text-tools/case-converter",
    features: ["Multiple formats", "Instant convert", "Bulk processing"],
    popular: false,
    usageCount: 12450,
    new: true,
  },
  {
    id: "line-break-remover",
    name: "Line Break Remover",
    description: "Remove or reduce line breaks and format text",
    category: "Text Tools",
    icon: ArrowDown,
    href: "/tools/text-tools/line-break-remover",
    features: ["Remove all breaks", "Keep single breaks", "Format text"],
    popular: false,
    usageCount: 5200,
    new: true,
  },
  {
    id: "duplicate-line-remover",
    name: "Duplicate Line Remover",
    description: "Remove duplicate lines and keep only unique entries",
    category: "Text Tools",
    icon: List,
    href: "/tools/text-tools/duplicate-line-remover",
    features: ["Case sensitive", "Stats display", "Clean lists"],
    popular: false,
    usageCount: 4800,
    new: true,
  },
  {
    id: "text-reverser",
    name: "Text Reverser",
    description: "Reverse text, words, or lines in multiple ways",
    category: "Text Tools",
    icon: RotateCcw,
    href: "/tools/text-tools/text-reverser",
    features: ["Reverse text", "Reverse words", "Reverse lines"],
    popular: false,
    usageCount: 3600,
    new: true,
  },
  {
    id: "whitespace-remover",
    name: "Whitespace Remover",
    description: "Remove extra spaces, tabs, and whitespace from text",
    category: "Text Tools",
    icon: Space,
    href: "/tools/text-tools/whitespace-remover",
    features: ["Remove extra", "Trim text", "Normalize format"],
    popular: false,
    usageCount: 6700,
    new: true,
  },
  {
    id: "find-replace",
    name: "Find and Replace",
    description: "Find and replace words or phrases in text",
    category: "Text Tools",
    icon: Search,
    href: "/tools/text-tools/find-replace",
    features: ["Case sensitive", "Replace all", "Count matches"],
    popular: false,
    usageCount: 8900,
    new: true,
  },
  {
    id: "text-sorting",
    name: "Text Sorting",
    description: "Sort text lines alphabetically or by length",
    category: "Text Tools",
    icon: ArrowUpDown,
    href: "/tools/text-tools/text-sorting",
    features: ["A-Z sorting", "Reverse sort", "Random shuffle"],
    popular: false,
    usageCount: 5100,
    new: true,
  },
  {
    id: "url-encoder-decoder",
    name: "URL Encoder/Decoder",
    description: "Encode or decode URLs and URI components",
    category: "Text Tools",
    icon: Link2,
    href: "/tools/text-tools/url-encoder-decoder",
    features: ["URL encode", "URL decode", "URI support"],
    popular: false,
    usageCount: 11200,
    new: true,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert between units of length, weight, temperature, and more",
    category: "Productivity",
    icon: Calculator,
    href: "/tools/productivity/unit-converter",
    features: ["50+ units", "Currency rates", "Instant convert"],
    popular: true,
    usageCount: 13890,
  },
  {
    id: "color-picker",
    name: "Color Picker",
    description: "Pick colors and convert between HEX, RGB, HSL, and more",
    category: "Productivity",
    icon: Palette,
    href: "/tools/productivity/color-picker",
    features: ["Multiple formats", "Color palettes", "Gradients"],
    popular: true,
    usageCount: 19670,
  },
  {
    id: "cheat-sheet-generator",
    name: "Cheat Sheet Generator",
    description: "Create searchable cheat sheets for Git, Docker, Tailwind and more",
    category: "Developer Tools",
    icon: BookOpen,
    href: "/tools/developer-tools/cheat-sheet-generator",
    features: ["Searchable commands", "Copy to clipboard", "Multiple categories"],
    popular: false,
    usageCount: 3200,
    new: true,
  },
  {
    id: "jekyll-config-builder",
    name: "Jekyll Config Builder",
    description: "Build Jekyll _config.yml files with an interactive visual interface",
    category: "Developer Tools",
    icon: Settings,
    href: "/tools/developer-tools/jekyll-config-builder",
    features: ["Live preview", "Download config", "Multi-step form"],
    popular: false,
    usageCount: 1800,
    new: true,
  },
  {
    id: "website-launch-checklist",
    name: "Website Launch Checklist",
    description: "Complete pre-launch checklist for SEO, performance, and security",
    category: "Productivity",
    icon: ClipboardCheck,
    href: "/tools/productivity/website-launch-checklist",
    features: ["Save progress", "Readiness score", "PDF report"],
    popular: false,
    usageCount: 4500,
    new: true,
  },
  {
    id: "json-playground",
    name: "JSON Playground",
    description: "Interactive JSON editor with beautify, minify, and validation",
    category: "Developer Tools",
    icon: Code,
    href: "/tools/developer-tools/json-playground",
    features: ["Syntax highlighting", "Error detection", "Large file support"],
    popular: false,
    usageCount: 7800,
    new: true,
  },
  {
    id: "freelance-tax-calculator",
    name: "Freelance Tax Calculator",
    description: "Calculate estimated taxes for freelancers and self-employed",
    category: "Productivity",
    icon: DollarSign,
    href: "/tools/productivity/freelance-tax-calculator",
    features: ["Visual breakdown", "Tax estimates", "Expense tracking"],
    popular: false,
    usageCount: 5600,
    new: true,
  },
  {
    id: "readme-generator",
    name: "README Generator",
    description: "Generate professional README.md files for your GitHub projects",
    category: "Developer Tools",
    icon: FileText,
    href: "/tools/developer-tools/readme-generator",
    features: ["Live preview", "Markdown export", "Badge support"],
    popular: false,
    usageCount: 9200,
    new: true,
  },
  {
    id: "seo-meta-generator",
    name: "SEO Meta Tag Generator",
    description: "Create optimized meta tags for Google, Facebook, and Twitter",
    category: "Developer Tools",
    icon: Search,
    href: "/tools/developer-tools/seo-meta-generator",
    features: ["Social previews", "Copy HTML", "Best practices"],
    popular: false,
    usageCount: 6700,
    new: true,
  },
  {
    id: "css-theme-generator",
    name: "CSS Theme Generator",
    description: "Build custom CSS themes with live preview and color pickers",
    category: "Developer Tools",
    icon: Paintbrush,
    href: "/tools/developer-tools/css-theme-generator",
    features: ["Live preview", "CSS variables", "Share themes"],
    popular: false,
    usageCount: 4100,
    new: true,
  },
  {
    id: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Generate .gitignore files for Node.js, Python, macOS, and more",
    category: "Developer Tools",
    icon: GitBranch,
    href: "/tools/developer-tools/gitignore-generator",
    features: ["Multiple templates", "Security warnings", "Custom rules"],
    popular: false,
    usageCount: 8900,
    new: true,
  },
  {
    id: "github-actions-generator",
    name: "GitHub Actions Generator",
    description: "Create GitHub Actions workflows with an easy wizard interface",
    category: "Developer Tools",
    icon: Workflow,
    href: "/tools/developer-tools/github-actions-generator",
    features: ["Step-by-step wizard", "Copy workflow", "Multiple templates"],
    popular: false,
    usageCount: 5300,
    new: true,
  },
]

export const categories: ToolCategory[] = [
  "AI Tools",
  "Developer Tools",
  "Image Tools",
  "Text Tools",
  "Productivity",
]

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((tool) => tool.category === category)
}

export function getPopularTools(): Tool[] {
  return tools.filter((tool) => tool.popular).sort((a, b) => (b.usageCount || 0) - (a.usageCount || 0))
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.new)
}

export function searchTools(query: string): Tool[] {
  const lowerQuery = query.toLowerCase()
  return tools.filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.features.some((feature) => feature.toLowerCase().includes(lowerQuery))
  )
}

export interface CategoryMetadata {
  name: ToolCategory
  slug: string
  icon: any
  description: string
  longDescription: string
  benefits: string[]
  targetAudience: string
  color: string
  gradient: string
  keywords: string[]
  lsiKeywords: string[]
  relatedCategories: ToolCategory[]
}

export const categoryMetadata: Record<ToolCategory, CategoryMetadata> = {
  "AI Tools": {
    name: "AI Tools",
    slug: "ai-tools",
    icon: Bot,
    description: "Powerful AI-powered tools for content creation, detection, and optimization",
    longDescription:
      "Harness the power of artificial intelligence with our comprehensive suite of AI tools. From humanizing AI-generated text to detecting AI content, our tools help you create authentic, high-quality content. Perfect for writers, marketers, students, and content creators who want to leverage AI technology while maintaining a natural, human touch in their work.",
    benefits: [
      "Save time with AI-powered automation",
      "Improve content quality and authenticity",
      "Detect and verify AI-generated content",
      "Generate human-like text instantly",
      "No technical knowledge required",
    ],
    targetAudience: "Content creators, writers, marketers, students, and professionals",
    color: "purple",
    gradient: "from-purple-500 to-pink-500",
    keywords: [
      "ai tools",
      "artificial intelligence",
      "ai text humanizer",
      "ai detector",
      "content generator",
      "paraphrasing tool",
    ],
    lsiKeywords: [
      "machine learning",
      "natural language processing",
      "content automation",
      "text generation",
      "ai writing assistant",
    ],
    relatedCategories: ["Text Tools", "Productivity", "Developer Tools"],
  },
  "Developer Tools": {
    name: "Developer Tools",
    slug: "developer-tools",
    icon: Code,
    description: "Professional development tools for programmers and developers",
    longDescription:
      "Streamline your development workflow with our comprehensive collection of developer tools. From formatting and validating JSON to testing regex patterns, debugging JWT tokens, and generating hashes, we provide everything developers need for efficient coding, debugging, and validation. All tools are free, fast, and work directly in your browser without any installation required.",
    benefits: [
      "Speed up development workflow",
      "Debug and validate code instantly",
      "No installation or setup needed",
      "Support for multiple languages and formats",
      "Save time with automated formatting",
    ],
    targetAudience: "Software developers, programmers, web developers, and IT professionals",
    color: "blue",
    gradient: "from-blue-500 to-cyan-500",
    keywords: [
      "developer tools",
      "code formatter",
      "json validator",
      "regex tester",
      "debugging tools",
      "syntax validator",
    ],
    lsiKeywords: [
      "coding",
      "programming",
      "debugging",
      "syntax",
      "validation",
      "minification",
      "beautify code",
    ],
    relatedCategories: ["Text Tools", "Productivity", "AI Tools"],
  },
  "Image Tools": {
    name: "Image Tools",
    slug: "image-tools",
    icon: ImageIcon,
    description: "Professional image editing and optimization tools for designers and creators",
    longDescription:
      "Transform your images with our powerful suite of image tools. Whether you need to compress images for faster loading, remove backgrounds, convert formats, or resize photos, our tools make image editing simple and efficient. Perfect for photographers, designers, marketers, and anyone who works with digital images. All processing happens in your browser for maximum privacy and speed.",
    benefits: [
      "Reduce image file sizes without quality loss",
      "Edit images without expensive software",
      "Batch process multiple images at once",
      "Maintain privacy with browser-based processing",
      "Professional results in seconds",
    ],
    targetAudience: "Photographers, graphic designers, web designers, marketers, and content creators",
    color: "green",
    gradient: "from-green-500 to-emerald-500",
    keywords: [
      "image tools",
      "photo editor",
      "image compressor",
      "background remover",
      "image optimizer",
      "graphic tools",
    ],
    lsiKeywords: [
      "photo",
      "graphic",
      "picture",
      "compress",
      "optimize",
      "resize",
      "convert",
      "editing",
    ],
    relatedCategories: ["Productivity", "Developer Tools", "Text Tools"],
  },
  "Text Tools": {
    name: "Text Tools",
    slug: "text-tools",
    icon: FileText,
    description: "Comprehensive text editing, formatting, and analysis tools",
    longDescription:
      "Master text manipulation with our extensive collection of text tools. From counting words and characters to converting case, finding differences, and generating Lorem Ipsum, we provide everything you need for text editing and analysis. Perfect for writers, editors, students, developers, and anyone who works with text content. All tools work instantly in your browser with real-time results.",
    benefits: [
      "Analyze text instantly with real-time counting",
      "Format and transform text effortlessly",
      "Compare and find differences in documents",
      "Generate placeholder content quickly",
      "No word limits or restrictions",
    ],
    targetAudience: "Writers, editors, students, content creators, and copywriters",
    color: "orange",
    gradient: "from-orange-500 to-red-500",
    keywords: [
      "text tools",
      "word counter",
      "character counter",
      "case converter",
      "text analyzer",
      "writing tools",
    ],
    lsiKeywords: [
      "writing",
      "document",
      "editor",
      "analysis",
      "formatting",
      "text processing",
      "word processing",
    ],
    relatedCategories: ["AI Tools", "Productivity", "Developer Tools"],
  },
  Productivity: {
    name: "Productivity",
    slug: "productivity",
    icon: Zap,
    description: "Essential productivity tools to boost your efficiency and save time",
    longDescription:
      "Supercharge your productivity with our collection of essential online tools. From generating secure passwords and QR codes to converting units and colors, we provide practical utilities that save you time every day. These tools are perfect for professionals, students, entrepreneurs, and anyone looking to work smarter and faster. Access everything you need without downloading software or creating accounts.",
    benefits: [
      "Save time with quick conversions and generators",
      "Enhance security with strong password generation",
      "Work more efficiently with practical utilities",
      "Access tools from any device, anywhere",
      "Completely free with no limitations",
    ],
    targetAudience: "Professionals, students, entrepreneurs, and anyone seeking efficiency",
    color: "yellow",
    gradient: "from-yellow-500 to-orange-500",
    keywords: [
      "productivity tools",
      "online utilities",
      "qr code generator",
      "password generator",
      "url shortener",
      "converter tools",
    ],
    lsiKeywords: [
      "efficiency",
      "utilities",
      "generators",
      "converters",
      "calculators",
      "time-saving",
      "automation",
    ],
    relatedCategories: ["Text Tools", "Developer Tools", "AI Tools"],
  },
}

export interface FAQ {
  question: string
  answer: string
}

export const categoryFAQs: Record<ToolCategory, FAQ[]> = {
  "AI Tools": [
    {
      question: "Are these AI tools really free?",
      answer:
        "Yes, all our AI tools are completely free to use with no hidden costs. You can access unlimited text humanization, AI detection, paraphrasing, and more without any subscription or payment.",
    },
    {
      question: "Do I need to create an account to use AI tools?",
      answer:
        "No account creation required! Simply visit any tool and start using it immediately. We believe in providing instant access to powerful AI technology without barriers.",
    },
    {
      question: "How accurate is the AI content detector?",
      answer:
        "Our AI content detector uses advanced algorithms to analyze text patterns, achieving high accuracy rates. While no detector is 100% perfect, our tool provides reliable results with detailed confidence scores.",
    },
    {
      question: "Is my data secure when using AI tools?",
      answer:
        "Absolutely. We prioritize your privacy and security. Your text is processed securely and we don't store, share, or use your content for any purpose. All processing happens in real-time and data is immediately discarded after results are delivered.",
    },
    {
      question: "Can I use these tools for commercial purposes?",
      answer:
        "Yes, you can use our AI tools for both personal and commercial projects. There are no restrictions on how you use the generated or processed content.",
    },
  ],
  "Developer Tools": [
    {
      question: "Are these developer tools really free?",
      answer:
        "Yes, all our developer tools are 100% free with no limitations. Format JSON, test regex, debug JWT, generate hashes, and more without any costs or subscriptions.",
    },
    {
      question: "Do I need to create an account?",
      answer:
        "No account needed! All tools work directly in your browser. Just open the tool and start using it immediately. No sign-up, no downloads, no hassle.",
    },
    {
      question: "Can I use these tools offline?",
      answer:
        "Most tools work in your browser and require an internet connection to load. However, once loaded, many tools like JSON formatter and Base64 encoder work entirely client-side for maximum privacy.",
    },
    {
      question: "Are my code and data secure?",
      answer:
        "Yes, your security is our priority. Most tools process data entirely in your browser without sending anything to our servers. For tools that require server processing, data is handled securely and immediately deleted after processing.",
    },
    {
      question: "How often are these tools updated?",
      answer:
        "We regularly update our tools to add new features, improve performance, and fix bugs. We also add new tools based on user feedback and emerging development needs.",
    },
  ],
  "Image Tools": [
    {
      question: "Are these image tools really free?",
      answer:
        "Yes, all our image tools are completely free to use. Compress, resize, crop, remove backgrounds, and convert images without any costs, watermarks, or limitations.",
    },
    {
      question: "Do I need to create an account?",
      answer:
        "No account required! Simply select your image and use any tool instantly. We provide immediate access to all image editing features without sign-up barriers.",
    },
    {
      question: "What file formats do you support?",
      answer:
        "We support all common image formats including JPG, PNG, WebP, GIF, BMP, and more. Our conversion tools can transform images between any of these formats easily.",
    },
    {
      question: "Are my images secure and private?",
      answer:
        "Absolutely. Most image processing happens directly in your browser for maximum privacy. Images are never stored on our servers, and any server-side processing is done securely with immediate deletion after processing.",
    },
    {
      question: "Is there a file size limit?",
      answer:
        "We support images up to 50MB for most tools. This covers the vast majority of use cases while ensuring fast processing. For larger files, consider compressing them first.",
    },
  ],
  "Text Tools": [
    {
      question: "Are these text tools really free?",
      answer:
        "Yes, all text tools are 100% free with no character limits, word count restrictions, or hidden fees. Use them as much as you need for personal or commercial projects.",
    },
    {
      question: "Do I need to create an account?",
      answer:
        "No account needed! All text tools work instantly in your browser. Just paste your text and get immediate results without any sign-up process.",
    },
    {
      question: "Is there a character or word limit?",
      answer:
        "No limits! Process as much text as you need. Whether you're working with a short paragraph or a lengthy document, our tools handle it efficiently.",
    },
    {
      question: "Are my documents and text secure?",
      answer:
        "Your privacy is paramount. All text processing happens in your browser whenever possible. We never store, share, or use your text content. Data is processed in real-time and immediately discarded.",
    },
    {
      question: "Can I use these tools for professional work?",
      answer:
        "Absolutely! Our text tools are designed for both personal and professional use. Writers, editors, students, and businesses use our tools daily for content creation, analysis, and formatting.",
    },
  ],
  Productivity: [
    {
      question: "Are these productivity tools really free?",
      answer:
        "Yes, all productivity tools are completely free to use with no restrictions. Generate passwords, create QR codes, shorten URLs, and convert units without any costs.",
    },
    {
      question: "Do I need to create an account?",
      answer:
        "No account creation required! Access all productivity tools instantly without sign-up. We believe in providing immediate value without barriers.",
    },
    {
      question: "Are generated passwords truly secure?",
      answer:
        "Yes, our password generator creates cryptographically secure random passwords using industry-standard algorithms. All generation happens in your browser for maximum security.",
    },
    {
      question: "Can I use these tools on mobile devices?",
      answer:
        "Absolutely! All tools are fully responsive and work perfectly on smartphones and tablets. Access your favorite productivity tools from any device, anywhere.",
    },
    {
      question: "How often do you add new tools?",
      answer:
        "We regularly add new productivity tools based on user requests and emerging needs. Check back often or follow us to discover new time-saving utilities.",
    },
  ],
}

export function getCategorySlug(category: ToolCategory): string {
  return categoryMetadata[category].slug
}

export function getCategoryFromSlug(slug: string): ToolCategory | null {
  const entry = Object.entries(categoryMetadata).find(([_, meta]) => meta.slug === slug)
  return entry ? (entry[0] as ToolCategory) : null
}

export function getCategoryIcon(category: ToolCategory) {
  return categoryMetadata[category].icon
}

export function getCategoryColor(category: ToolCategory) {
  return categoryMetadata[category].color
}

export function getCategoryGradient(category: ToolCategory) {
  return categoryMetadata[category].gradient
}
